name: publish-site
on:
  push:
    branches:
      - main  # 当你向 main 分支推送代码时触发
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24  # 使用Node.js 24
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-jupyter
      - run: mkdocs gh-deploy --force
      
